apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rsocket-simulation.fullname" . }}
  labels:
    {{- include "rsocket-simulation.labels" . | nindent 4 }}
spec:
  completionMode: Indexed
  completions: {{ .Values.simulation.shards }}
  parallelism: {{ min .Values.simulation.parallelism .Values.simulation.shards }}
  backoffLimitPerIndex: {{ .Values.job.backoffLimitPerIndex }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "rsocket-simulation.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      containers:
        - name: simulator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "rsocket-simulation.fullname" . }}
          env:
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
